name: HypixelThePit
version: ${project.version}
main: net.swofty.hypixelthepit.Loader

commands:
  test:
    description: f
  randomleveltest:
    description: f
  setlevel:
    description: f
  respawn:
    description: f
  setxp:
    description: f
  setgold:
    description: f
  debugholograms:
    description: f
  gmgui:
    description: f
  debugnpc:
    description: f
  lobby:
    description: f
  simulatedeath:
    description: f
  simulatekill:
    description: f
  stats:
    description: f